### ISSUE TITLE
Does not work when compiled via PyInstaller

### ISSUE THREAD

**Issue by sserver224** [harfang3d/dogfight-sandbox-hg2#48]
Run exe output: 
`(0:051:583:200) Harfang core 1.2.0 (build 1538b3acd3c9351b7b9108742a5f352c98b78e5d Feb  7 2019 09:51:22)
(0:056:555:200) See http://harfang3d.com/license for licensing terms
(0:204:585:600) Load plugins from 4 default paths
(0:206:580:300) Scanning for plugin in 'c:/Users/fitbi/'...
(0:211:050:000) error: LoadSharedLibrary('sfextra.dll') failed, reason: %1 is not a valid Win32 application.

(0:215:589:600) 0 plugin(s) loaded
(0:217:320:100) Scanning for plugin in 'c:/Users/fitbi/AppData/Local/Temp/_MEI184562/base_library.zip/harfang/'...
(0:222:930:200) 0 plugin(s) loaded
(0:224:276:900) Scanning for plugin in 'c:/Users/fitbi/AppData/Local/Temp/_MEI184562/lib-dynload/harfang/'...
(0:229:429:900) 0 plugin(s) loaded
(0:231:235:200) Scanning for plugin in 'c:/Users/fitbi/AppData/Local/Temp/_MEI184562/harfang/'...
(0:236:044:700) 0 plugin(s) loaded
(0:238:165:200) 0 plugin(s) loaded
(0:240:725:100) Mount root driver 000002236AEAE4B0 (relative to '')
(0:256:356:600) warn: No renderer available, was LoadPlugins called successfully?
Traceback (most recent call last):
  File "flight_sim.py", line 4232, in <module>
  File "flight_sim.py", line 2575, in request_screen_mode
RuntimeError: RenderInit failed, was LoadPlugins called succesfully?`

**Comment by astrofra** [comment]
Hi,

Thank you for your interest in the Harfang projects :)

your error log reports you are building a PyInstaller version of the Dogfight on Harfang `1.2.0`, however, the [current version](https://github.com/harfang3d/dogfight-sandbox-hg2) of the dogfight requires Harfang `3.2.x`.

Could this be the source of this issue ? Could you make sure you have only one version of Harfang installer on your setup ?
