### ISSUE TITLE
pip install harfang==3.2.5 failed, please help me.

### ISSUE THREAD

**Issue by jiangwei2005** [harfang3d/dogfight-sandbox-hg2#88]
Collecting harfang==3.2.5
Using cached harfang-3.2.5.tar.gz (49.1 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: harfang
Building wheel for harfang (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for harfang (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [180 lines of output]
running bdist_wheel
running build
running build_ext
-- The CXX compiler identification is GNU 9.4.0
-- The C compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking FabGen path
-- Checking FabGen path - ok
-- Building for 64-bit
-- Found Python3: /home/jiangwei/anaconda3/envs/dogfight2/bin/python3.9 (found version "3.9.19") found components: Interpreter Development Development.Module Development.Embed
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Using X11 for window creation
-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
CMake Deprecation Warning at extern/bgfx/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  CMake Deprecation Warning at extern/bgfx/bx.cmake:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  Call Stack (most recent call first):
    extern/bgfx/CMakeLists.txt:8 (include)
  
  
  CMake Deprecation Warning at extern/bgfx/bimg.cmake:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  Call Stack (most recent call first):
    extern/bgfx/CMakeLists.txt:9 (include)
  
  
  CMake Deprecation Warning at extern/bgfx/bgfx.cmake:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  Call Stack (most recent call first):
    extern/bgfx/CMakeLists.txt:10 (include)
  
  
  CMake Warning (dev) at /tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.29/Modules/FindOpenGL.cmake:415 (message):
    Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
    available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.
  
    FindOpenGL found both a legacy GL library:
  
      OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
  
    and GLVND libraries for OpenGL and GLX:
  
      OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
      OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
  
    OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
    compatibility with CMake 3.10 and below the legacy GL library will be used.
  Call Stack (most recent call first):
    extern/bgfx/bgfx.cmake:102 (find_package)
    extern/bgfx/CMakeLists.txt:10 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
  -- OpenGL version: 33
  CMake Deprecation Warning at extern/bgfx/tools.cmake:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  Call Stack (most recent call first):
    extern/bgfx/CMakeLists.txt:12 (include)
  
  
  CMake Error at /tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find readline (missing: READLINE_LIBRARY READLINE_INCLUDE_DIR)
  Call Stack (most recent call first):
    /tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/cmake/data/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    harfang/cmake/Findreadline.cmake:20 (find_package_handle_standard_args)
    extern/CMakeLists.txt:131 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  
  ==> Configuring:
  $ cmake -S /tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1 -B /tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/build/temp.linux-x86_64-cpython-39_CMakeProject -G Ninja -DCMAKE_MAKE_PROGRAM=/tmp/pip-build-env-t9uuocwj/overlay/bin/ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/build/lib.linux-x86_64-cpython-39/harfang -DPython3_EXECUTABLE:FILEPATH=/home/jiangwei/anaconda3/envs/dogfight2/bin/python3.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH:PATH=/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/harfang/cmake -DHG_FABGEN_PATH:PATH=/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/extern/fabgen -DHG_BUILD_ASSETC:BOOL=ON -DHG_BUILD_CPP_SDK:BOOL=OFF -DHG_REBUILD_GLFW:BOOL=ON -DHG_BUILD_TESTS:BOOL=OFF -DHG_BUILD_FBX_CONVERTER:BOOL=OFF -DHG_BUILD_GLTF_IMPORTER:BOOL=ON -DHG_BUILD_GLTF_EXPORTER:BOOL=ON -DHG_BUILD_ASSIMP_CONVERTER:BOOL=ON -DHG_BUILD_HG_LUA:BOOL=OFF -DHG_BUILD_HG_PYTHON:BOOL=ON -DHG_PYTHON_PIP:BOOL=ON -DHG_BUILD_HG_GO:BOOL=OFF -DHG_ENABLE_OPENVR_API:BOOL=ON -DHG_ENABLE_RECAST_DETOUR_API:BOOL=OFF -DHG_BUILD_DOCS:BOOL=OFF -DHG_COMMIT_ID:STRING=200d2a60a25346a9930b1e96103023aaac50480a
  
  ==> Building:
  $ cmake --build /tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/build/temp.linux-x86_64-cpython-39_CMakeProject --config Release
  
  ==> Installing:
  $ cmake --install /tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/build/temp.linux-x86_64-cpython-39_CMakeProject --config Release
  
  Traceback (most recent call last):
    File "/home/jiangwei/anaconda3/envs/dogfight2/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/jiangwei/anaconda3/envs/dogfight2/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/jiangwei/anaconda3/envs/dogfight2/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 410, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 183, in <module>
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/cmake_build_extension/build_extension.py", line 114, in run
      self.build_extension(ext)
    File "<string>", line 53, in build_extension
    File "/tmp/pip-build-env-t9uuocwj/overlay/lib/python3.9/site-packages/cmake_build_extension/build_extension.py", line 241, in build_extension
      subprocess.check_call(configure_command)
    File "/home/jiangwei/anaconda3/envs/dogfight2/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1', '-B', '/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/build/temp.linux-x86_64-cpython-39_CMakeProject', '-G', 'Ninja', '-DCMAKE_MAKE_PROGRAM=/tmp/pip-build-env-t9uuocwj/overlay/bin/ninja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/build/lib.linux-x86_64-cpython-39/harfang', '-DPython3_EXECUTABLE:FILEPATH=/home/jiangwei/anaconda3/envs/dogfight2/bin/python3.9', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_MODULE_PATH:PATH=/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/harfang/cmake', '-DHG_FABGEN_PATH:PATH=/tmp/pip-install-1rl9sogy/harfang_5ccf62ffe5744895a571ed474a9eb6a1/extern/fabgen', '-DHG_BUILD_ASSETC:BOOL=ON', '-DHG_BUILD_CPP_SDK:BOOL=OFF', '-DHG_REBUILD_GLFW:BOOL=ON', '-DHG_BUILD_TESTS:BOOL=OFF', '-DHG_BUILD_FBX_CONVERTER:BOOL=OFF', '-DHG_BUILD_GLTF_IMPORTER:BOOL=ON', '-DHG_BUILD_GLTF_EXPORTER:BOOL=ON', '-DHG_BUILD_ASSIMP_CONVERTER:BOOL=ON', '-DHG_BUILD_HG_LUA:BOOL=OFF', '-DHG_BUILD_HG_PYTHON:BOOL=ON', '-DHG_PYTHON_PIP:BOOL=ON', '-DHG_BUILD_HG_GO:BOOL=OFF', '-DHG_ENABLE_OPENVR_API:BOOL=ON', '-DHG_ENABLE_RECAST_DETOUR_API:BOOL=OFF', '-DHG_BUILD_DOCS:BOOL=OFF', '-DHG_COMMIT_ID:STRING=200d2a60a25346a9930b1e96103023aaac50480a']' returned non-zero exit status 1.
  [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for harfang
Failed to build harfang
ERROR: Could not build wheels for harfang, which is required to install pyproject.toml-based projects

**Comment by jiangwei2005** [comment]
In Ubuntu, pip install harfang==3.2.5 is failed,  install harfang wheel file is success.
